#ifndef EDS_INFO_HXX
#define EDS_INFO_HXX
#define EDS_VERSION_MAJOR 0
#define EDS_VERSION_MINOR 1
#define EDS_VERSION_CANDIDATE 0
#define EDS_VERSION_BUILD 230
#define EDS_VERSION EDS_VERSION_MAJOR.EDS_VERSION_MINOR.EDS_VERSION_CANDIDATE.EDS_VERSION_BUILD
#define EDS_DESCRIPTION "Event Delegate Subscription"
#define EDS_HOMEPAGE_URL "https://github.com/JackDMenendez/eds"
#endif // EDS_INFO_HXX
